<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, reactive } from 'vue';
import { api, payload, exportData, parseImport, message, exitProfile, type ProxyItem, type ProxyInput, type ImportRow, type Observation } from './egress';
const rows = ref<ProxyItem[]>([]), loading = ref(true), loadError = ref(''), notice = ref(''), actionError = ref('');
const search = ref(''), protocol = ref(''), status = ref(''), selected = ref<string[]>([]);
const drawerID = ref(''), editing = ref<ProxyItem | null>(null), modal = ref<'edit' | 'import' | 'delete' | null>(null);
const saving = ref(false), running = ref(new Set<string>()), deleting = ref<ProxyItem | null>(null);
const importText = ref(''), imported = ref<ImportRow[]>([]);
const form = reactive({ name: '', protocol: 'socks5', host: '', port: 7891, username: '', password: '', clear_auth: false, tag: '', note: '', expires_at: '' });
const detail = computed(() => rows.value.find(r => r.proxy_id === drawerID.value));
const isTesting = (r: ProxyItem) => r.testing || running.value.has(r.proxy_id);
const expired = (r: ProxyItem) => !!r.expires_at && Date.parse(r.expires_at) <= Date.now();
const state = (r: ProxyItem) => isTesting(r) ? 'testing' : expired(r) ? 'expired' : r.status;
const stateNames: Record<string, string> = { active: '连通通过', pending: '待测试', off: '已停用', testing: '测试中', expired: '已过期' };
const filtered = computed(() => rows.value.filter(r => (!search.value || `${r.name} ${r.host} ${r.tag}`.toLowerCase().includes(search.value.toLowerCase())) && (!protocol.value || r.protocol === protocol.value) && (!status.value || state(r) === status.value)));
const active = computed(() => rows.value.filter(r => state(r) === 'active').length);
const recent = computed(() => rows.value.map(r => r.probe?.finished_at).filter((v): v is string => !!v).sort().at(-1));
const allSelected = computed(() => filtered.value.length > 0 && filtered.value.every(r => selected.value.includes(r.proxy_id)));
const date = (v?: string | null) => v ? new Date(v).toLocaleString('zh-CN', { hour12: false }) : '尚无记录';
const flag = (v: boolean | null | undefined) => v === true ? '来源已标记' : v === false ? '来源未标记' : '未知';
const location = (o?: Observation) => [o?.country, o?.region, o?.city].filter(Boolean).join(' / ') || '未获取';
const profiles = computed(() => Object.fromEntries(rows.value.map(row => [row.proxy_id, exitProfile(row.probe)])));
const flagFiles = import.meta.glob<string>('../../node_modules/flag-icons/flags/4x3/*.svg', { eager: true, query: '?url&no-inline', import: 'default' });
const flagURL = (code: string) => flagFiles[`../../node_modules/flag-icons/flags/4x3/${code.toLowerCase()}.svg`];
const geoTitle = (row: ProxyItem) => { const p = profiles.value[row.proxy_id]; return p.geo ? `位置来源：${p.geo.source}${p.fallback ? '（备用来源）' : ''}${row.probe?.location_conflict ? '；来源存在差异，见详情' : ''}` : '尚无可用地理观测'; };
const quality = (r: ProxyItem) => r.probe?.observations.some(o => o.status === 'available' && [o.datacenter, o.proxy, o.vpn, o.tor, o.risk_score].some(v => v !== null && v !== undefined)) ? '已有来源数据' : r.probe ? '信息未获取' : '未检测';
function replace(row: ProxyItem) { const index = rows.value.findIndex(r => r.proxy_id === row.proxy_id); if (index < 0) rows.value.unshift(row); else rows.value[index] = row; }
async function refresh() { loading.value = true; loadError.value = ''; try { rows.value = (await api<{ items: ProxyItem[] }>()).items; selected.value = selected.value.filter(id => rows.value.some(r => r.proxy_id === id)); } catch (e) { rows.value = []; loadError.value = (e as Error).message; } finally { loading.value = false; } }
function edit(row?: ProxyItem) { editing.value = row || null; actionError.value = ''; drawerID.value = ''; Object.assign(form, row ? { ...payload(row), username: '', password: '', clear_auth: false, expires_at: row.expires_at ? new Date(Date.parse(row.expires_at) - new Date(row.expires_at).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : '' } : { name: '', protocol: 'socks5', host: '', port: 7891, username: '', password: '', clear_auth: false, tag: '', note: '', expires_at: '' }); modal.value = 'edit'; }
async function save() { saving.value = true; actionError.value = ''; notice.value = ''; try { const input: ProxyInput = { name: form.name, protocol: form.protocol, host: form.host, port: Number(form.port), tag: form.tag, note: form.note, expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : '', ...(editing.value ? { revision: editing.value.revision } : {}) }; if (form.clear_auth) input.clear_auth = true; else { if (form.username) input.username = form.username; if (form.password) input.password = form.password; } replace((await api<{ item: ProxyItem }>(editing.value ? `/${editing.value.proxy_id}` : '', editing.value ? 'PUT' : 'POST', input)).item); modal.value = null; form.username = ''; form.password = ''; notice.value = '代理已保存。请运行检测查看实测出口及 IP 库信息。'; } catch (e) { actionError.value = (e as Error).message; } finally { saving.value = false; } }
async function test(row: ProxyItem) { if (isTesting(row)) return; running.value.add(row.proxy_id); actionError.value = ''; notice.value = ''; try { const item = (await api<{ item: ProxyItem }>(`/${row.proxy_id}/test`, 'POST', {})).item; replace(item); notice.value = item.probe?.status === 'passed' ? '连通检测完成，请查看实测出口及 IP 库来源。' : '代理检测失败，请查看各次检测结果。'; } catch (e) { actionError.value = (e as Error).message; } finally { running.value.delete(row.proxy_id); } }
async function batch() { for (const id of [...selected.value]) { const row = rows.value.find(r => r.proxy_id === id); if (row && row.status !== 'off' && !expired(row)) await test(row); } }
async function toggle(row: ProxyItem) { actionError.value = ''; notice.value = ''; try { replace((await api<{ item: ProxyItem }>(`/${row.proxy_id}`, 'PUT', { ...payload(row), status: row.status === 'off' ? 'pending' : 'off' })).item); notice.value = '代理管理状态已保存'; } catch (e) { actionError.value = (e as Error).message; } }
function selectAll() { selected.value = allSelected.value ? selected.value.filter(id => !filtered.value.some(r => r.proxy_id === id)) : [...new Set([...selected.value, ...filtered.value.map(r => r.proxy_id)])]; }
function askDelete(row: ProxyItem) { deleting.value = row; modal.value = 'delete'; actionError.value = ''; }
async function remove() { if (!deleting.value) return; saving.value = true; try { await api(`/${deleting.value.proxy_id}`, 'DELETE'); rows.value = rows.value.filter(r => r.proxy_id !== deleting.value!.proxy_id); selected.value = selected.value.filter(id => id !== deleting.value!.proxy_id); drawerID.value = ''; modal.value = null; notice.value = '代理已删除'; } catch (e) { actionError.value = (e as Error).message; } finally { saving.value = false; } }
function exportFile() { const url = URL.createObjectURL(new Blob([JSON.stringify(exportData(filtered.value), null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `station-proxies-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notice.value = '脱敏导出已下载；认证凭据不包含在文件中。'; }
function preview() { actionError.value = ''; notice.value = ''; try { imported.value = parseImport(importText.value, rows.value); } catch (e) { imported.value = []; actionError.value = (e as Error).message; } }
async function importFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 256 * 1024) { actionError.value = '文件不能超过 256 KiB'; return; } importText.value = await file.text(); preview(); }
async function commitImport() { saving.value = true; for (const item of imported.value) { if (item.state !== 'valid' || !item.input) continue; try { replace((await api<{ item: ProxyItem }>('', 'POST', item.input)).item); item.state = 'imported'; item.detail = '已保存；请检测，认证未导出的记录需补填'; } catch (e) { item.state = 'failed'; item.detail = (e as Error).message; } } importText.value = ''; for (const item of imported.value) if (item.input) { delete item.input.username; delete item.input.password; } saving.value = false; }
function closeModal() { if (saving.value) return; modal.value = null; actionError.value = ''; form.username = ''; form.password = ''; importText.value = ''; imported.value = []; }
onMounted(() => { refresh(); window.addEventListener('studio:login-success', refresh); });
onUnmounted(() => window.removeEventListener('studio:login-success', refresh));
</script>

<template>
 <div class="proxy-page"><main class="main"><div class="workspace proxy-workspace">
  <header class="heading"><div class="heading-left"><span class="eyebrow">STATION · NETWORK EGRESS</span><h1>网络出口</h1><p>保存代理，检查真实出口、连通质量与 IP 库信息。</p></div><div class="heading-actions"><button class="btn" :disabled="loading" @click="refresh">刷新状态</button><button class="btn primary" @click="edit()">＋ 添加代理</button></div></header>
  <p v-if="notice" class="review-note" role="status">{{ notice }}</p><p v-if="actionError && !modal" class="error" role="alert">{{ actionError }}</p>
  <section class="proxy-metrics"><article><span>代理总数</span><strong>{{ rows.length }}</strong><small>当前组织</small></article><article><span>连通通过</span><strong class="ok">{{ active }}</strong><small>最近检测通过且未过期</small></article><article><span>待测试</span><strong>{{ rows.filter(r => r.status === 'pending').length }}</strong><small>新增或配置已更新</small></article><article><span>检测中</span><strong>{{ rows.filter(isTesting).length }}</strong><small>逐次真实请求</small></article><article><span>最近检测</span><strong class="metric-time">{{ date(recent) }}</strong><small>历史观测时间</small></article></section>
  <section class="proxy-panel"><div class="proxy-toolbar"><label class="proxy-search"><input v-model="search" aria-label="搜索代理名称或地址" placeholder="搜索代理名称、地址或标签" /></label><select v-model="protocol" aria-label="协议筛选"><option value="">协议：全部</option><option v-for="p in ['http', 'https', 'socks5', 'socks5h']" :key="p" :value="p">{{ p.toUpperCase() }}</option></select><select v-model="status" aria-label="状态筛选"><option value="">状态：全部</option><option v-for="(label, key) in stateNames" :key="key" :value="key">{{ label }}</option></select><button class="btn" @click="modal = 'import'; actionError = ''; imported = []">导入</button><button class="btn" :disabled="loading || !!loadError" @click="exportFile">导出</button></div>
   <div v-if="selected.length" class="selection">已选择 {{ selected.length }} 项 <button class="btn" :disabled="running.size > 0" @click="batch">批量检测</button></div>
   <div v-if="loading" class="empty" role="status">正在读取代理…</div><div v-else-if="loadError" class="empty error" role="alert">{{ loadError }} <button class="btn" @click="refresh">重试</button></div><div v-else-if="!filtered.length" class="empty">{{ rows.length ? '没有匹配的代理，请调整筛选条件。' : '尚未添加代理。' }} <button class="btn" @click="edit()">＋ 添加代理</button></div>
   <div v-else class="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="选择全部代理" :checked="allSelected" @change="selectAll" /></th><th>代理</th><th>地址</th><th>出口 IP</th><th>连接质量</th><th>IP 质量</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.proxy_id"><td><input v-model="selected" type="checkbox" :value="row.proxy_id" :aria-label="`选择 ${row.name}`" /></td><td><button class="proxy-name" @click="drawerID = row.proxy_id">{{ row.name }}</button><small>{{ row.protocol.toUpperCase() }} · {{ row.tag || '无标签' }}</small></td><td><code>{{ row.host }}:{{ row.port }}</code><small>{{ row.auth_configured ? '认证已配置' : '无认证' }}</small></td><td class="exit-profile">
     <code>{{ row.probe?.exit_ip || '尚未探测' }}</code>
     <small class="exit-location" :title="geoTitle(row)"><img v-if="flagURL(profiles[row.proxy_id].countryCode)" class="country-flag" :src="flagURL(profiles[row.proxy_id].countryCode)" alt="" />{{ profiles[row.proxy_id].location }}<button v-if="row.probe?.location_conflict" class="location-difference warn" aria-label="查看地理来源差异" @click="drawerID = row.proxy_id">ⓘ</button></small>
     <small class="exit-type" :title="profiles[row.proxy_id].typeEvidence">{{ profiles[row.proxy_id].type }}</small>
    </td><td>{{ row.probe?.successes ? `${row.probe.mean_latency_ms} ms` : '—' }}<small v-if="row.probe">{{ row.probe.successes }}/{{ row.probe.attempts }} 次成功</small></td><td>{{ quality(row) }}<small v-if="row.probe">{{ date(row.probe.finished_at) }}</small></td><td :class="row.status === 'active' ? 'ok' : ''">{{ stateNames[state(row)] }}<small v-if="row.probe?.status === 'failed'" class="error">最近检测失败</small></td><td class="row-actions"><button class="icon-button" @click="drawerID = row.proxy_id">详情</button><button class="icon-button" :disabled="isTesting(row) || row.status === 'off' || expired(row)" @click="test(row)">检测</button><button class="icon-button" @click="edit(row)">编辑</button><button class="icon-button" @click="toggle(row)">{{ row.status === 'off' ? '启用' : '停用' }}</button><button class="icon-button" :disabled="!!row.assigned_apps.length || isTesting(row)" @click="askDelete(row)">删除</button></td></tr></tbody></table></div>
   <footer class="table-footer">显示 {{ filtered.length }} 个代理</footer></section><p class="proxy-footnote">连通通过不代表供应商可用或 IP 无风险。检测数据保留时间与来源，重新检测可更新观测。</p>
 </div></main>
 <template v-if="detail"><div class="drawer-shade" @click="drawerID = ''"></div><aside class="proxy-drawer" aria-label="代理详情"><header><div><span class="eyebrow">PROXY ENDPOINT</span><h2>{{ detail.name }}</h2><small>{{ detail.proxy_id }}</small></div><button class="drawer-close" aria-label="关闭详情" @click="drawerID = ''">×</button></header>
  <div class="drawer-body"><section><h3>代理配置</h3><dl><div><dt>端点</dt><dd>{{ detail.protocol }}://{{ detail.host }}:{{ detail.port }}</dd></div><div><dt>认证</dt><dd>{{ detail.auth_configured ? '已配置，凭据不回显' : '未配置' }}</dd></div><div><dt>有效期</dt><dd>{{ detail.expires_at ? date(detail.expires_at) : '长期有效' }}</dd></div><div><dt>管理员备注</dt><dd>{{ detail.note || '无' }}</dd></div></dl><button class="btn primary" :disabled="isTesting(detail) || detail.status === 'off' || expired(detail)" @click="test(detail)">{{ isTesting(detail) ? '检测中…' : '检测出口与 IP 质量' }}</button></section>
  <template v-if="detail.probe"><section><h3>连通与稳定性</h3><dl><div><dt>出口 IP</dt><dd>{{ detail.probe.exit_ip || '未获取' }}</dd></div><div><dt>结果</dt><dd>{{ detail.probe.status === 'passed' ? '连通通过' : '检测失败' }}</dd></div><div><dt>采样成功率</dt><dd>{{ detail.probe.successes }}/{{ detail.probe.attempts }}（{{ detail.probe.success_rate.toFixed(0) }}%）</dd></div><div><dt>平均耗时 / 极差</dt><dd>{{ detail.probe.mean_latency_ms }} / {{ detail.probe.jitter_ms }} ms</dd></div><div><dt>采样窗口</dt><dd>{{ date(detail.probe.started_at) }} 至 {{ date(detail.probe.finished_at) }}</dd></div><div><dt>固定目标</dt><dd>{{ detail.probe.target }}</dd></div></dl><p class="probe-explain">三次独立连接的短时观测，不代表长期稳定性。</p><p v-if="detail.probe.exit_changed" class="warn">本次观察到多个出口 IP；信息查询对应首次成功的 IP。</p><ul><li v-for="(sample, index) in detail.probe.samples" :key="index">第 {{ index + 1 }} 次 · {{ sample.latency_ms }} ms · {{ sample.error ? message(sample.error) : sample.ip }}</li></ul></section>
  <section><h3>出口画像</h3><dl><div><dt>国家／州／城市</dt><dd>{{ profiles[detail.proxy_id].location }}</dd></div><div><dt>地理来源</dt><dd>{{ profiles[detail.proxy_id].geo?.source || '未获取' }}{{ profiles[detail.proxy_id].fallback ? '（备用来源）' : '' }}</dd></div><div><dt>IP 类型</dt><dd>{{ profiles[detail.proxy_id].type }}</dd></div><div><dt>类型依据</dt><dd>{{ profiles[detail.proxy_id].typeEvidence }}</dd></div></dl><p class="probe-explain">地理位置来自出口 IP 数据库。按 IPinfo、ipapi.is、IPQuery 的顺序选取可用来源。</p><p v-if="detail.probe.location_conflict" class="warn">来源的定位或 ASN 存在差异，原始观测如下。</p></section>
  <section v-for="source in detail.probe.observations" :key="source.source"><h3>{{ source.source }}</h3><small>{{ date(source.at) }} · {{ source.ip }}</small><p v-if="source.status !== 'available'" class="error">信息未获取：{{ message(source.error || '') }}</p><template v-else><dl><div><dt>IP 库推测位置</dt><dd>{{ location(source) }}</dd></div><div><dt>ASN</dt><dd>{{ source.asn || '未知' }}</dd></div><div><dt>运营商 / 组织</dt><dd>{{ source.isp || source.organization || '未知' }}</dd></div></dl><template v-if="source.source === 'IPQuery'"><dl><div><dt>数据中心</dt><dd>{{ flag(source.datacenter) }}</dd></div><div><dt>代理 / VPN</dt><dd>{{ flag(source.proxy) }} / {{ flag(source.vpn) }}</dd></div><div><dt>Tor / 移动网络</dt><dd>{{ flag(source.tor) }} / {{ flag(source.mobile) }}</dd></div><div><dt>来源风险分值</dt><dd>{{ source.risk_score === null ? '未知' : `${source.risk_score} / 100` }}</dd></div></dl><p class="probe-explain">标签与分值来自 IPQuery；未标记不保证无风险，非数据中心也不能据此确认住宅 IP。</p></template></template><a :href="source.url" target="_blank" rel="noopener noreferrer">查看该信息源</a></section><section><h3>名单级信誉</h3><p class="probe-explain">未检测具体黑名单；不把来源风险分值解释为黑名单全通过。</p></section></template><p v-else class="empty">尚无检测结果。点击检测后查看实测出口、连通质量及 IP 库观测。</p></div></aside></template>
 <div v-if="modal" class="modal-shade" @click.self="closeModal"><section class="proxy-modal" role="dialog" aria-modal="true" :aria-label="modal === 'edit' ? '代理编辑' : modal === 'import' ? '导入代理' : '删除代理'"><header><h2>{{ modal === 'edit' ? editing ? '编辑代理' : '添加代理' : modal === 'import' ? '导入代理' : '删除代理' }}</h2><button type="button" class="drawer-close" :disabled="saving" aria-label="关闭弹窗" @click="closeModal">×</button></header><p v-if="actionError" class="error" role="alert">{{ actionError }}</p>
 <form v-if="modal === 'edit'" @submit.prevent="save"><div class="form-grid"><label class="full">名称<input v-model="form.name" required maxlength="120" /></label><label>协议<select v-model="form.protocol"><option v-for="p in ['socks5', 'socks5h', 'http', 'https']" :key="p" :value="p">{{ p.toUpperCase() }}</option></select></label><label>端口<input v-model.number="form.port" type="number" required min="1" max="65535" /></label><label class="full">主机<input v-model="form.host" required placeholder="proxy.example.net" /></label><label>用户名<input v-model="form.username" :disabled="form.clear_auth" autocomplete="off" maxlength="255" :placeholder="editing?.auth_configured ? '留空保留已有认证' : '可选'" /></label><label>密码<input v-model="form.password" :disabled="form.clear_auth" type="password" autocomplete="new-password" maxlength="255" placeholder="留空保留，填写则更新" /></label><label v-if="editing?.auth_configured" class="full inline"><input v-model="form.clear_auth" type="checkbox" />明确清空已有认证</label><label>有效期<input v-model="form.expires_at" type="datetime-local" /></label><label>标签<input v-model="form.tag" maxlength="256" /></label><label class="full">备注<textarea v-model="form.note" maxlength="4000"></textarea></label></div><p class="secret">凭据加密保存，不回显。保存后运行检测，更新出口 IP、位置和类型。</p><footer><button type="button" class="btn" :disabled="saving" @click="closeModal">取消</button><button class="btn primary" :disabled="saving">{{ saving ? '保存中…' : '保存代理' }}</button></footer></form>
 <div v-else-if="modal === 'import'" class="import-body"><label>代理 URL（每行一条）或脱敏 JSON<textarea v-model="importText" :disabled="saving" @input="imported = []"></textarea></label><label>选择导入文件<input type="file" accept=".json,.txt" :disabled="saving" @change="importFile" /></label><p class="probe-explain">最多 50 条。脱敏导出不含凭据，认证代理导入后需重新填写。</p><ol><li v-for="item in imported" :key="item.line">第 {{ item.line }} 条：{{ item.input?.name || '无效记录' }} — {{ item.detail }}</li></ol><footer><button class="btn" :disabled="saving" @click="preview">预览解析</button><button class="btn primary" :disabled="saving || !imported.some(r => r.state === 'valid')" @click="commitImport">{{ saving ? '导入中…' : '确认导入' }}</button><button class="btn" :disabled="saving" @click="closeModal">关闭</button></footer></div>
 <div v-else class="delete-body"><p>删除“{{ deleting?.name }}”后不能恢复。仍被引用的代理不能删除。</p><footer><button class="btn" :disabled="saving" @click="closeModal">取消</button><button class="btn danger" :disabled="saving" @click="remove">确认删除</button></footer></div>
 </section></div></div>
</template>
<style scoped src="./station-proxy.css"></style>
<style scoped>
.exit-profile{min-width:220px}.table-wrap .exit-location{display:flex;align-items:center;gap:5px}.country-flag{width:18px;height:14px;object-fit:contain;flex-shrink:0}.location-difference{border:0;background:transparent;padding:0;cursor:pointer;font-size:12px}.table-wrap .exit-type{color:var(--ink)}.error{color:var(--danger)}button:disabled{opacity:.45;cursor:not-allowed}.proxy-metrics .metric-time{font-size:14px;line-height:1.5}.table-wrap td{white-space:normal;min-width:70px}.table-wrap code{overflow-wrap:anywhere}.row-actions{min-width:140px}.proxy-drawer{width:min(590px,100vw)}.drawer-body dd{overflow-wrap:anywhere;white-space:pre-wrap}.drawer-body a{color:var(--accent);font-size:12px}.drawer-body li,.import-body li{font-size:12px;line-height:1.8}.proxy-modal .error{padding:0 20px}.inline{display:flex;flex-direction:row;align-items:center}.inline input{width:auto}.proxy-modal{max-height:90dvh;overflow:auto}.proxy-metrics article{min-width:0}
</style>
